#!/usr/bin/env ruby

require 'rubygems'
require 'aws/s3'

access_key_file = ENV["S3_ACCESS_KEY"]
secret_access_key_file = ENV["S3_SECRET_ACCESS_KEY"]

if access_key_file == nil || !File.exists?(access_key_file)
  STDERR.puts "Access key not found"
  exit 1
end

if secret_access_key_file == nil || !File.exists?(secret_access_key_file)
  STDERR.puts "Secret access key not found"
  exit 1
end

access_key = open(access_key_file).read.strip
secret_access_key = open(secret_access_key_file).read.strip

AWS::S3::Base.establish_connection!(:access_key_id => access_key, :secret_access_key => secret_access_key)

Dir["db/*.dump"].each do |backup|
  data = File.open(backup, "rb")
  filename = data.mtime.strftime("%Y-%m-%d.%H:%M.dump")
  puts filename
  #AWS::S3::S3Object.store(filename, data.read, "danbooru-backup", :access => :private)
end
