#!/usr/bin/env bash

cat public/stylesheets/default.css | sed -e 's/^ *//g; s/ *$//g; s/\([:{;,]\) /\1/g; s/ {/{/g; s/\/\*.*\*\///g; /^$/d' | sed -e :a -e '$!N; s/\n\(.\)/\1/; ta' > public/stylesheets/default-min.css
