#!/bin/env ruby

require "rubygems"
require "postgres"

db = PGconn.new("127.0.0.1", nil, nil, nil, "danbooru")

db.exec("BEGIN TRANSACTION")

# Fix post counts
db.exec("UPDATE tags SET post_count = (SELECT COUNT(*) FROM posts_tags pt WHERE pt.tag_id = tags.id)")

# Delete empty tags
db.exec("DELETE FROM tags WHERE post_count = 0 AND id NOT IN (SELECT alias_id FROM tag_aliases) AND id NOT IN (SELECT parent_id FROM tag_implications) AND id NOT IN (SELECT child_id FROM tag_implications)")

# Fix cached tags
res = db.exec("SELECT id FROM posts")
res.result.each do |id|
	tags = db.exec("SELECT t.name FROM tags t, posts_tags pt WHERE t.id = pt.tag_id AND pt.post_id = #{id[0]} ORDER BY t.name").result.flatten.join(" ")
	q_tags = PGconn.quote(tags)
	db.exec("UPDATE posts SET cached_tags = #{q_tags} WHERE id = #{id}")
end

db.exec("COMMIT TRANSACTION")
