#!/bin/bash

export RAILS_ENV=production
cd "$(dirname $0)/../../"
script/donmai/downbooru
mongrel_rails cluster::stop
app/daemons/job_task_processor_ctl.rb stop
rake maint:purge_tags maint:recalculate_row_count
script/donmai/backup_db
script/donmai/backup_db_to_s3
script/donmai/backup_svn_to_s3
sudo script/donmai/process_logs
sudo script/donmai/rotate_logs
script/donmai/prune_unapproved_posts
script/donmai/prune_old_job_tasks
script/donmai/prune_unactivated_users
script/donmai/prune_backup_dbs
if [[ `date '+%d'` -eq '01' ]] ; then 
  script/donmai/dump_related_tags
fi
if [[ `date '+%d'` -eq '01' ]] ; then
  script/donmai/dump_tags
fi
script/donmai/send_moderator_report
app/daemons/job_task_processor_ctl.rb start
mongrel_rails cluster::start
sleep 5
script/donmai/upbooru
