#!/bin/sh

script/donmai/downbooru
#mongrel_rails cluster::stop
app/daemons/job_task_processor_ctl.rb stop
svn update
sleep 5
RAILS_ENV=production rake db:migrate
script/build_application_js
app/daemons/job_task_processor_ctl.rb start
touch tmp/restart.txt
#mongrel_rails cluster::start
sleep 10
script/donmai/upbooru
