#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../../config/environment'

Thread.current["inside_batch"] = true

user = User.find(1)

Post.find(:all, :conditions => ["status = 'pending' and created_at < ? ", 3.days.ago], :select => "id").each do |post|
  Post.destroy_with_reason(post.id, "Unapproved in three days", user)
end

Post.find(:all, :conditions => ["status = 'flagged'"]).each do |post|
  if post.flags.unresolved.old.any?
    Post.destroy_with_reason(post.id, "Unapproved in three days after returning to moderation queue", user)
  end
end

ModAction.destroy_all(["user_id = 1 and description like ?", "deleted post %"])
