#!/bin/sh

script/donmai/downbooru
#mongrel_rails cluster::stop
DB_HOST=dbserver app/daemons/job_task_processor_ctl.rb stop
sleep 10
touch tmp/restart.txt
DB_HOST=dbserver app/daemons/job_task_processor_ctl.rb start
#mongrel_rails cluster::start
sleep 10
script/donmai/upbooru
